# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        MainWindow.setStyleSheet("QmainWindow#MainWindow,QWidget#widget,#widget_2{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QWidget#widget_5{\n"
"background-color: rgb(240, 241, 245);\n"
"}\n"
"QPushButton#btn_resolve_report,#btn_person_info,#btn_resolve_vid{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    /*border-radius: 3.2px;\n"
"    min-width: 96px;\n"
"    max-width: 96px;\n"
"    min-height: 96px;\n"
"    max-height: 96px;*/\n"
"    font:bold 11pt;\n"
"}\n"
"QPushButton#btn_resolve_report::hover,#btn_person_info::hover,#btn_resolve_vid::hover{    \n"
"    background-color: rgb(219, 225, 255);\n"
"    border-right: 1px solid rgb(11, 126, 216);\n"
"    font:bold 12pt;\n"
"}\n"
"QPushButton#btn_resolve_report:pressed,#btn_person_info:pressed,#btn_resolve_vid:pressed{    \n"
"    background-color: rgb(204, 228, 247);\n"
"    border: 1px solid rgb(0, 85, 155);\n"
"    font:bold 11pt;\n"
"}\n"
"QPushButton#btn_resolve_report:checked,#btn_person_info:checked,#btn_resolve_vid:checked{    \n"
"    background-color: rgb(204, 228, 247);\n"
"    border-right: 2px solid rgb(74, 127, 244);\n"
"    font:bold 11pt;\n"
"}\n"
"QPushButton#btn_update_image{\n"
"background-image: url(:/image/头像.png);\n"
"background-origin: content;\n"
"background-position: top;\n"
"padding-top: 15px;\n"
"background-repeat: no-repeat;\n"
"text-align: bottom;\n"
"border: 1px solid rgb(173, 173, 173);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 40px;\n"
"}")
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        self.widget_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 89, 245);")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lab_title = QtWidgets.QLabel(self.widget_7)
        self.lab_title.setMinimumSize(QtCore.QSize(80, 40))
        self.lab_title.setStyleSheet("font:bold 18pt;")
        self.lab_title.setObjectName("lab_title")
        self.horizontalLayout.addWidget(self.lab_title)
        self.lab_head = QtWidgets.QLabel(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_head.sizePolicy().hasHeightForWidth())
        self.lab_head.setSizePolicy(sizePolicy)
        self.lab_head.setMinimumSize(QtCore.QSize(50, 40))
        self.lab_head.setMaximumSize(QtCore.QSize(50, 40))
        self.lab_head.setStyleSheet("font:bold 18pt;\n"
"border-image: url(:/image/头像.png);")
        self.lab_head.setText("")
        self.lab_head.setObjectName("lab_head")
        self.horizontalLayout.addWidget(self.lab_head)
        self.btn_name = QtWidgets.QPushButton(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_name.sizePolicy().hasHeightForWidth())
        self.btn_name.setSizePolicy(sizePolicy)
        self.btn_name.setStyleSheet("font:bold 18pt;\n"
"background:transparent;")
        self.btn_name.setObjectName("btn_name")
        self.horizontalLayout.addWidget(self.btn_name)
        self.btn_quit = QtWidgets.QPushButton(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_quit.sizePolicy().hasHeightForWidth())
        self.btn_quit.setSizePolicy(sizePolicy)
        self.btn_quit.setMinimumSize(QtCore.QSize(33, 33))
        self.btn_quit.setMaximumSize(QtCore.QSize(33, 33))
        self.btn_quit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/关闭退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_quit.setIcon(icon)
        self.btn_quit.setIconSize(QtCore.QSize(25, 25))
        self.btn_quit.setFlat(True)
        self.btn_quit.setObjectName("btn_quit")
        self.horizontalLayout.addWidget(self.btn_quit)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget = QtWidgets.QWidget(self.widget_6)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_resolve_vid = QtWidgets.QPushButton(self.widget)
        self.btn_resolve_vid.setMinimumSize(QtCore.QSize(0, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/视频解析.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_resolve_vid.setIcon(icon1)
        self.btn_resolve_vid.setCheckable(True)
        self.btn_resolve_vid.setAutoRepeat(True)
        self.btn_resolve_vid.setObjectName("btn_resolve_vid")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.btn_resolve_vid)
        self.verticalLayout.addWidget(self.btn_resolve_vid)
        self.btn_resolve_report = QtWidgets.QPushButton(self.widget)
        self.btn_resolve_report.setMinimumSize(QtCore.QSize(0, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/报告解析.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_resolve_report.setIcon(icon2)
        self.btn_resolve_report.setCheckable(True)
        self.btn_resolve_report.setAutoRepeat(True)
        self.btn_resolve_report.setObjectName("btn_resolve_report")
        self.buttonGroup.addButton(self.btn_resolve_report)
        self.verticalLayout.addWidget(self.btn_resolve_report)
        spacerItem = QtWidgets.QSpacerItem(20, 652, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_person_manage = QtWidgets.QPushButton(self.widget)
        self.btn_person_manage.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_person_manage.setFont(font)
        self.btn_person_manage.setStyleSheet("background:transparent;")
        self.btn_person_manage.setIcon(icon1)
        self.btn_person_manage.setCheckable(True)
        self.btn_person_manage.setAutoRepeat(True)
        self.btn_person_manage.setObjectName("btn_person_manage")
        self.buttonGroup.addButton(self.btn_person_manage)
        self.verticalLayout.addWidget(self.btn_person_manage)
        self.horizontalLayout_5.addWidget(self.widget)
        self.widget_5 = QtWidgets.QWidget(self.widget_6)
        self.widget_5.setStyleSheet("")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_5)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.widget_5)
        self.horizontalLayout_5.setStretch(0, 150)
        self.horizontalLayout_5.setStretch(1, 850)
        self.verticalLayout_2.addWidget(self.widget_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icon/关闭退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_resolve_vid, self.btn_resolve_report)
        MainWindow.setTabOrder(self.btn_resolve_report, self.btn_person_manage)
        MainWindow.setTabOrder(self.btn_person_manage, self.btn_quit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "孔洞识别系统"))
        self.lab_title.setText(_translate("MainWindow", "logo"))
        self.btn_name.setText(_translate("MainWindow", "logo"))
        self.btn_resolve_vid.setText(_translate("MainWindow", " 视频解析"))
        self.btn_resolve_report.setText(_translate("MainWindow", " 报告解析"))
        self.btn_person_manage.setText(_translate("MainWindow", "  人员管理"))
        self.actionExit.setText(_translate("MainWindow", "关闭"))
import picture_rc
