# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personal_center.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WgtPersonalCenter(object):
    def setupUi(self, WgtPersonalCenter):
        WgtPersonalCenter.setObjectName("WgtPersonalCenter")
        WgtPersonalCenter.resize(976, 794)
        WgtPersonalCenter.setMinimumSize(QtCore.QSize(976, 794))
        WgtPersonalCenter.setMaximumSize(QtCore.QSize(976, 794))
        WgtPersonalCenter.setWindowTitle("")
        WgtPersonalCenter.setStyleSheet("QmainWindow#MainWindow,QWidget#widget,#widget_2{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QWidget#widget_5{\n"
"background-color: rgb(240, 241, 245);\n"
"}\n"
"QPushButton#btn_resolve_report,#btn_person_info,#btn_resolve_vid{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    /*border-radius: 3.2px;\n"
"    min-width: 96px;\n"
"    max-width: 96px;\n"
"    min-height: 96px;\n"
"    max-height: 96px;*/\n"
"    font:bold 11pt;\n"
"}\n"
"QPushButton#btn_resolve_report::hover,#btn_person_info::hover,#btn_resolve_vid::hover{    \n"
"    background-color: rgb(219, 225, 255);\n"
"    border-right: 1px solid rgb(11, 126, 216);\n"
"    font:bold 12pt;\n"
"}\n"
"QPushButton#btn_resolve_report:pressed,#btn_person_info:pressed,#btn_resolve_vid:pressed{    \n"
"    background-color: rgb(204, 228, 247);\n"
"    border: 1px solid rgb(0, 85, 155);\n"
"    font:bold 11pt;\n"
"}\n"
"QPushButton#btn_resolve_report:checked,#btn_person_info:checked,#btn_resolve_vid:checked{    \n"
"    background-color: rgb(204, 228, 247);\n"
"    border-right: 2px solid rgb(74, 127, 244);\n"
"    font:bold 11pt;\n"
"}\n"
"QPushButton#btn_update_image{\n"
"background-image: url(:/image/头像.png);\n"
"background-origin: content;\n"
"background-position: top;\n"
"padding-top: 15px;\n"
"background-repeat: no-repeat;\n"
"text-align: bottom;\n"
"border: 1px solid rgb(173, 173, 173);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 40px;\n"
"}")
        self.gridLayout_3 = QtWidgets.QGridLayout(WgtPersonalCenter)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(WgtPersonalCenter)
        self.widget_2.setObjectName("widget_2")
        self.btn_update_image = QtWidgets.QPushButton(self.widget_2)
        self.btn_update_image.setGeometry(QtCore.QRect(470, 70, 80, 80))
        self.btn_update_image.setMinimumSize(QtCore.QSize(80, 80))
        self.btn_update_image.setMaximumSize(QtCore.QSize(80, 80))
        self.btn_update_image.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_update_image.setAutoFillBackground(False)
        self.btn_update_image.setStyleSheet("")
        self.btn_update_image.setInputMethodHints(QtCore.Qt.ImhNone)
        self.btn_update_image.setObjectName("btn_update_image")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(310, 160, 391, 271))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setMinimumSize(QtCore.QSize(60, 28))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.edt_name = QtWidgets.QLineEdit(self.widget_3)
        self.edt_name.setMinimumSize(QtCore.QSize(0, 25))
        self.edt_name.setObjectName("edt_name")
        self.gridLayout.addWidget(self.edt_name, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setMinimumSize(QtCore.QSize(60, 28))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 1, 1, 1)
        self.edt_role = QtWidgets.QLineEdit(self.widget_3)
        self.edt_role.setMinimumSize(QtCore.QSize(0, 25))
        self.edt_role.setObjectName("edt_role")
        self.gridLayout.addWidget(self.edt_role, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setMinimumSize(QtCore.QSize(60, 28))
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 1, 1, 1)
        self.edt_phone_number = QtWidgets.QLineEdit(self.widget_3)
        self.edt_phone_number.setMinimumSize(QtCore.QSize(0, 25))
        self.edt_phone_number.setObjectName("edt_phone_number")
        self.gridLayout.addWidget(self.edt_phone_number, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setMinimumSize(QtCore.QSize(60, 28))
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 1, 1, 1)
        self.edt_mail = QtWidgets.QLineEdit(self.widget_3)
        self.edt_mail.setMinimumSize(QtCore.QSize(0, 25))
        self.edt_mail.setObjectName("edt_mail")
        self.gridLayout.addWidget(self.edt_mail, 4, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_change_user_info = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_change_user_info.sizePolicy().hasHeightForWidth())
        self.btn_change_user_info.setSizePolicy(sizePolicy)
        self.btn_change_user_info.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_change_user_info.setFont(font)
        self.btn_change_user_info.setStyleSheet("background-color: rgb(19, 89, 245);")
        self.btn_change_user_info.setObjectName("btn_change_user_info")
        self.horizontalLayout_2.addWidget(self.btn_change_user_info)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 1, 1, 2)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(310, 440, 391, 271))
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setMinimumSize(QtCore.QSize(60, 28))
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 1, 1, 1)
        self.edt_old_pwd = QtWidgets.QLineEdit(self.widget_4)
        self.edt_old_pwd.setMinimumSize(QtCore.QSize(0, 25))
        self.edt_old_pwd.setObjectName("edt_old_pwd")
        self.gridLayout_2.addWidget(self.edt_old_pwd, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setMinimumSize(QtCore.QSize(60, 28))
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 1, 1, 1)
        self.edt_new_pwd = QtWidgets.QLineEdit(self.widget_4)
        self.edt_new_pwd.setMinimumSize(QtCore.QSize(0, 25))
        self.edt_new_pwd.setObjectName("edt_new_pwd")
        self.gridLayout_2.addWidget(self.edt_new_pwd, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setMinimumSize(QtCore.QSize(60, 28))
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 1, 1, 1)
        self.edt_confirm_pwd = QtWidgets.QLineEdit(self.widget_4)
        self.edt_confirm_pwd.setMinimumSize(QtCore.QSize(0, 25))
        self.edt_confirm_pwd.setObjectName("edt_confirm_pwd")
        self.gridLayout_2.addWidget(self.edt_confirm_pwd, 3, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btn_change_pwd = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_change_pwd.sizePolicy().hasHeightForWidth())
        self.btn_change_pwd.setSizePolicy(sizePolicy)
        self.btn_change_pwd.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_change_pwd.setFont(font)
        self.btn_change_pwd.setStyleSheet("background-color: rgb(18, 89, 243);")
        self.btn_change_pwd.setObjectName("btn_change_pwd")
        self.horizontalLayout_3.addWidget(self.btn_change_pwd)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(100, 20, 91, 31))
        self.label_4.setStyleSheet("font: 87 14pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(390, 60, 61, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../image/头像.png"))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 1)

        self.retranslateUi(WgtPersonalCenter)
        QtCore.QMetaObject.connectSlotsByName(WgtPersonalCenter)

    def retranslateUi(self, WgtPersonalCenter):
        _translate = QtCore.QCoreApplication.translate
        self.btn_update_image.setText(_translate("WgtPersonalCenter", "上传头像"))
        self.label_6.setText(_translate("WgtPersonalCenter", "基础信息"))
        self.label_8.setText(_translate("WgtPersonalCenter", "姓名"))
        self.label_9.setText(_translate("WgtPersonalCenter", "角色"))
        self.label_10.setText(_translate("WgtPersonalCenter", "手机号"))
        self.edt_phone_number.setPlaceholderText(_translate("WgtPersonalCenter", "请输入您的手机号"))
        self.label_11.setText(_translate("WgtPersonalCenter", "邮箱"))
        self.edt_mail.setPlaceholderText(_translate("WgtPersonalCenter", "请输入您的邮箱"))
        self.btn_change_user_info.setText(_translate("WgtPersonalCenter", "确定修改"))
        self.label_7.setText(_translate("WgtPersonalCenter", "重置密码"))
        self.label_12.setText(_translate("WgtPersonalCenter", "旧密码"))
        self.edt_old_pwd.setPlaceholderText(_translate("WgtPersonalCenter", "请输入原来密码"))
        self.label_13.setText(_translate("WgtPersonalCenter", "新密码"))
        self.edt_new_pwd.setPlaceholderText(_translate("WgtPersonalCenter", "请输入新密码"))
        self.label_14.setText(_translate("WgtPersonalCenter", "确认密码"))
        self.edt_confirm_pwd.setPlaceholderText(_translate("WgtPersonalCenter", "请确认密码"))
        self.btn_change_pwd.setText(_translate("WgtPersonalCenter", "确认重置密码"))
        self.label_4.setText(_translate("WgtPersonalCenter", "个人中心"))
import picture_rc
