# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'person_manage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WgtPersonManage(object):
    def setupUi(self, WgtPersonManage):
        WgtPersonManage.setObjectName("WgtPersonManage")
        WgtPersonManage.resize(976, 794)
        WgtPersonManage.setMinimumSize(QtCore.QSize(976, 794))
        WgtPersonManage.setMaximumSize(QtCore.QSize(976, 794))
        WgtPersonManage.setStyleSheet("QmainWindow#MainWindow,QWidget#widget,#widget_2{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QWidget#widget_5{\n"
"background-color: rgb(240, 241, 245);\n"
"}\n"
"QPushButton#btn_resolve_report,#btn_person_info,#btn_resolve_vid{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    /*border-radius: 3.2px;\n"
"    min-width: 96px;\n"
"    max-width: 96px;\n"
"    min-height: 96px;\n"
"    max-height: 96px;*/\n"
"    font:bold 11pt;\n"
"}\n"
"QPushButton#btn_resolve_report::hover,#btn_person_info::hover,#btn_resolve_vid::hover{    \n"
"    background-color: rgb(219, 225, 255);\n"
"    border-right: 1px solid rgb(11, 126, 216);\n"
"    font:bold 12pt;\n"
"}\n"
"QPushButton#btn_resolve_report:pressed,#btn_person_info:pressed,#btn_resolve_vid:pressed{    \n"
"    background-color: rgb(204, 228, 247);\n"
"    border: 1px solid rgb(0, 85, 155);\n"
"    font:bold 11pt;\n"
"}\n"
"QPushButton#btn_resolve_report:checked,#btn_person_info:checked,#btn_resolve_vid:checked{    \n"
"    background-color: rgb(204, 228, 247);\n"
"    border-right: 2px solid rgb(74, 127, 244);\n"
"    font:bold 11pt;\n"
"}\n"
"QPushButton#btn_update_image{\n"
"background-image: url(:/image/头像.png);\n"
"background-origin: content;\n"
"background-position: top;\n"
"padding-top: 15px;\n"
"background-repeat: no-repeat;\n"
"text-align: bottom;\n"
"border: 1px solid rgb(173, 173, 173);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 40px;\n"
"}")
        self.gridLayout_3 = QtWidgets.QGridLayout(WgtPersonManage)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(WgtPersonManage)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setStyleSheet("font: 87 14pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edt_phone = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_phone.sizePolicy().hasHeightForWidth())
        self.edt_phone.setSizePolicy(sizePolicy)
        self.edt_phone.setObjectName("edt_phone")
        self.horizontalLayout_2.addWidget(self.edt_phone)
        self.btn_query = QtWidgets.QPushButton(self.widget_2)
        self.btn_query.setMinimumSize(QtCore.QSize(75, 23))
        self.btn_query.setStyleSheet("background-color: rgb(19, 89, 245);\n"
"color: rgb(255, 255, 255);\n"
"border:0px solid rgb(19, 89, 245);")
        self.btn_query.setObjectName("btn_query")
        self.horizontalLayout_2.addWidget(self.btn_query)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_add_person = QtWidgets.QPushButton(self.widget_2)
        self.btn_add_person.setMinimumSize(QtCore.QSize(75, 23))
        self.btn_add_person.setStyleSheet("background-color: rgb(19, 89, 245);\n"
"color: rgb(255, 255, 255);\n"
"border:0px solid rgb(19, 89, 245);")
        self.btn_add_person.setObjectName("btn_add_person")
        self.horizontalLayout_2.addWidget(self.btn_add_person)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../image/头像.png"))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_total_count = QtWidgets.QLabel(self.widget_2)
        self.label_total_count.setMinimumSize(QtCore.QSize(72, 0))
        self.label_total_count.setStyleSheet("font: 87 14pt \"Arial\";")
        self.label_total_count.setObjectName("label_total_count")
        self.horizontalLayout_4.addWidget(self.label_total_count)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btn_pre_page = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pre_page.sizePolicy().hasHeightForWidth())
        self.btn_pre_page.setSizePolicy(sizePolicy)
        self.btn_pre_page.setMinimumSize(QtCore.QSize(75, 23))
        self.btn_pre_page.setStyleSheet("background-color: rgb(19, 89, 245);\n"
"color: rgb(255, 255, 255);\n"
"border:0px solid rgb(19, 89, 245);")
        self.btn_pre_page.setObjectName("btn_pre_page")
        self.horizontalLayout_4.addWidget(self.btn_pre_page)
        self.label_cur_page = QtWidgets.QLabel(self.widget_2)
        self.label_cur_page.setMinimumSize(QtCore.QSize(60, 0))
        self.label_cur_page.setStyleSheet("font: 87 14pt \"Arial\";")
        self.label_cur_page.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cur_page.setObjectName("label_cur_page")
        self.horizontalLayout_4.addWidget(self.label_cur_page)
        self.btn_next_page = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next_page.sizePolicy().hasHeightForWidth())
        self.btn_next_page.setSizePolicy(sizePolicy)
        self.btn_next_page.setMinimumSize(QtCore.QSize(75, 23))
        self.btn_next_page.setStyleSheet("background-color: rgb(19, 89, 245);\n"
"color: rgb(255, 255, 255);\n"
"border:0px solid rgb(19, 89, 245);")
        self.btn_next_page.setObjectName("btn_next_page")
        self.horizontalLayout_4.addWidget(self.btn_next_page)
        self.label_total_page = QtWidgets.QLabel(self.widget_2)
        self.label_total_page.setMinimumSize(QtCore.QSize(60, 0))
        self.label_total_page.setStyleSheet("font: 87 14pt \"Arial\";")
        self.label_total_page.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total_page.setObjectName("label_total_page")
        self.horizontalLayout_4.addWidget(self.label_total_page)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setStyleSheet("font: 87 14pt \"Arial\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.comboBox_page_count = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_page_count.sizePolicy().hasHeightForWidth())
        self.comboBox_page_count.setSizePolicy(sizePolicy)
        self.comboBox_page_count.setObjectName("comboBox_page_count")
        self.horizontalLayout_4.addWidget(self.comboBox_page_count)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 3)
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 1)

        self.retranslateUi(WgtPersonManage)
        QtCore.QMetaObject.connectSlotsByName(WgtPersonManage)
        WgtPersonManage.setTabOrder(self.edt_phone, self.btn_query)
        WgtPersonManage.setTabOrder(self.btn_query, self.btn_add_person)
        WgtPersonManage.setTabOrder(self.btn_add_person, self.tableWidget)

    def retranslateUi(self, WgtPersonManage):
        _translate = QtCore.QCoreApplication.translate
        WgtPersonManage.setWindowTitle(_translate("WgtPersonManage", "人员管理"))
        self.label_4.setText(_translate("WgtPersonManage", "人员管理"))
        self.edt_phone.setPlaceholderText(_translate("WgtPersonManage", "请输入手机号"))
        self.btn_query.setText(_translate("WgtPersonManage", "查询"))
        self.btn_add_person.setText(_translate("WgtPersonManage", "+ 添加人员"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("WgtPersonManage", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("WgtPersonManage", "角色"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("WgtPersonManage", "邮箱"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("WgtPersonManage", "手机号"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("WgtPersonManage", "状态"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("WgtPersonManage", "操作"))
        self.label_total_count.setText(_translate("WgtPersonManage", "共0条"))
        self.btn_pre_page.setText(_translate("WgtPersonManage", "上一页"))
        self.label_cur_page.setText(_translate("WgtPersonManage", "1"))
        self.btn_next_page.setText(_translate("WgtPersonManage", "下一页"))
        self.label_total_page.setText(_translate("WgtPersonManage", "共 1 页"))
        self.label_11.setText(_translate("WgtPersonManage", "每页显示"))
import picture_rc
