# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quit_win_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WgtQuitWinDisplay(object):
    def setupUi(self, WgtQuitWinDisplay):
        WgtQuitWinDisplay.setObjectName("WgtQuitWinDisplay")
        WgtQuitWinDisplay.resize(240, 180)
        WgtQuitWinDisplay.setMinimumSize(QtCore.QSize(240, 180))
        WgtQuitWinDisplay.setMaximumSize(QtCore.QSize(240, 180))
        WgtQuitWinDisplay.setStyleSheet("QWidget#widget{\n"
"border:1px solid rgba(19, 89, 245, 150);\n"
"border-radius:3.2px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(WgtQuitWinDisplay)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(WgtQuitWinDisplay)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setStyleSheet("font:bold 12pt;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(19, 89, 245);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_exit = QtWidgets.QPushButton(self.widget_2)
        self.btn_exit.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_exit.setStyleSheet("background-color: rgb(18, 89, 243);")
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout_2.addWidget(self.btn_exit)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_cancel = QtWidgets.QPushButton(self.widget_2)
        self.btn_cancel.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_cancel.setStyleSheet("background-color: rgb(18, 89, 243);")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout.setStretch(2, 10)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(WgtQuitWinDisplay)
        QtCore.QMetaObject.connectSlotsByName(WgtQuitWinDisplay)

    def retranslateUi(self, WgtQuitWinDisplay):
        _translate = QtCore.QCoreApplication.translate
        WgtQuitWinDisplay.setWindowTitle(_translate("WgtQuitWinDisplay", "退出"))
        self.label.setText(_translate("WgtQuitWinDisplay", "确认退出"))
        self.label_2.setText(_translate("WgtQuitWinDisplay", "确定要退出当前系统吗？"))
        self.btn_exit.setText(_translate("WgtQuitWinDisplay", "确认退出"))
        self.btn_cancel.setText(_translate("WgtQuitWinDisplay", "取消"))
