# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'single_hole_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WgtSingleHoleDisplay(object):
    def setupUi(self, WgtSingleHoleDisplay):
        WgtSingleHoleDisplay.setObjectName("WgtSingleHoleDisplay")
        WgtSingleHoleDisplay.resize(459, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WgtSingleHoleDisplay.sizePolicy().hasHeightForWidth())
        WgtSingleHoleDisplay.setSizePolicy(sizePolicy)
        WgtSingleHoleDisplay.setStyleSheet("background-color: rgb(241, 245, 255);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(WgtSingleHoleDisplay)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lab_hole_img_display = QtWidgets.QLabel(WgtSingleHoleDisplay)
        self.lab_hole_img_display.setObjectName("lab_hole_img_display")
        self.horizontalLayout.addWidget(self.lab_hole_img_display)
        self.widget = QtWidgets.QWidget(WgtSingleHoleDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.lab_width_display = QtWidgets.QLabel(self.widget)
        self.lab_width_display.setObjectName("lab_width_display")
        self.gridLayout.addWidget(self.lab_width_display, 3, 1, 1, 1)
        self.label_hint_width = QtWidgets.QLabel(self.widget)
        self.label_hint_width.setObjectName("label_hint_width")
        self.gridLayout.addWidget(self.label_hint_width, 3, 0, 1, 1)
        self.lab_hint_depth = QtWidgets.QLabel(self.widget)
        self.lab_hint_depth.setObjectName("lab_hint_depth")
        self.gridLayout.addWidget(self.lab_hint_depth, 5, 0, 1, 1)
        self.lab_hint_duration = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_hint_duration.sizePolicy().hasHeightForWidth())
        self.lab_hint_duration.setSizePolicy(sizePolicy)
        self.lab_hint_duration.setObjectName("lab_hint_duration")
        self.gridLayout.addWidget(self.lab_hint_duration, 1, 0, 1, 1)
        self.lab_duration_display = QtWidgets.QLabel(self.widget)
        self.lab_duration_display.setObjectName("lab_duration_display")
        self.gridLayout.addWidget(self.lab_duration_display, 1, 1, 1, 1)
        self.lab_height_display = QtWidgets.QLabel(self.widget)
        self.lab_height_display.setObjectName("lab_height_display")
        self.gridLayout.addWidget(self.lab_height_display, 2, 1, 1, 1)
        self.lab_hint_area = QtWidgets.QLabel(self.widget)
        self.lab_hint_area.setObjectName("lab_hint_area")
        self.gridLayout.addWidget(self.lab_hint_area, 4, 0, 1, 1)
        self.lab_hole_id = QtWidgets.QLabel(self.widget)
        self.lab_hole_id.setObjectName("lab_hole_id")
        self.gridLayout.addWidget(self.lab_hole_id, 0, 0, 1, 1)
        self.lab_depth_display = QtWidgets.QLabel(self.widget)
        self.lab_depth_display.setObjectName("lab_depth_display")
        self.gridLayout.addWidget(self.lab_depth_display, 5, 1, 1, 1)
        self.lab_hint_height = QtWidgets.QLabel(self.widget)
        self.lab_hint_height.setObjectName("lab_hint_height")
        self.gridLayout.addWidget(self.lab_hint_height, 2, 0, 1, 1)
        self.lab_area_display = QtWidgets.QLabel(self.widget)
        self.lab_area_display.setObjectName("lab_area_display")
        self.gridLayout.addWidget(self.lab_area_display, 4, 1, 1, 1)
        self.btn_delete = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete.sizePolicy().hasHeightForWidth())
        self.btn_delete.setSizePolicy(sizePolicy)
        self.btn_delete.setStyleSheet("background-color: rgb(19, 89, 245);\n"
"color: rgb(255, 255, 255);")
        self.btn_delete.setObjectName("btn_delete")
        self.gridLayout.addWidget(self.btn_delete, 6, 0, 1, 1)
        self.lab_from_display = QtWidgets.QLabel(self.widget)
        self.lab_from_display.setStyleSheet("background-color: rgb(19, 89, 245);\n"
"color: rgb(255, 255, 255);")
        self.lab_from_display.setObjectName("lab_from_display")
        self.gridLayout.addWidget(self.lab_from_display, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(WgtSingleHoleDisplay)
        QtCore.QMetaObject.connectSlotsByName(WgtSingleHoleDisplay)

    def retranslateUi(self, WgtSingleHoleDisplay):
        _translate = QtCore.QCoreApplication.translate
        self.label_hint_width.setText(_translate("WgtSingleHoleDisplay", "短轴尺寸："))
        self.lab_hint_depth.setText(_translate("WgtSingleHoleDisplay", "深度："))
        self.lab_hint_duration.setText(_translate("WgtSingleHoleDisplay", "片段时间："))
        self.lab_hint_area.setText(_translate("WgtSingleHoleDisplay", "面积："))
        self.lab_hole_id.setText(_translate("WgtSingleHoleDisplay", "孔洞"))
        self.lab_hint_height.setText(_translate("WgtSingleHoleDisplay", "长轴尺寸："))
        self.btn_delete.setText(_translate("WgtSingleHoleDisplay", "删除"))
        self.lab_from_display.setText(_translate("WgtSingleHoleDisplay", "手动解析"))
